### ISSUE TITLE
Image not loaded after webpack

### ISSUE THREAD

**Issue by DaKaZ** [peter-jozsa/react-native-web-image-loader#6]
This is probably user / implementation error, but I am hoping someone can help me out because its driving me nuts.  I have a react-native project I am using react-native-web with webpack to out an HTML version of the app.  The iOS version of the app works perfectly and places the image on the screen.  In the web version, everything is working EXCEPT for image loading.  Here is what I have in my webpack configuration:

```
      {
        test: /\.(png|jpe?g|gif)$/,
        include: [path.resolve(__dirname, "../../client/src/assets/images")],
        exclude: [path.resolve(__dirname, "../../client/node_modules")],
        loader: "react-native-web-image-loader?name=[name]-[hash].[ext]"
      }
```

When I run webpack, I can see the image being processed:
```
                      _/_/client/src/assets/images/Logo-White-Large-5469ae2c62722b55416c0ca6f1dbba39.gif    54.7 kB          [emitted]         
                                                   Logo-White-Large-30623336086a09a195315f12170a9aee.gif  140 bytes          [emitted]
```
and if I look at the output, I see the file without the path exports the actual image:
```
$ cat public/packs/Logo-White-Large-30623336086a09a195315f12170a9aee.gif 
module.exports = __webpack_public_path__ + "_/_/client/src/assets/images/Logo-White-Large-5469ae2c62722b55416c0ca6f1dbba39.gif";
```
and `_/_/client/src/assets/images/Logo-White-Large-5469ae2c62722b55416c0ca6f1dbba39.gif` is the actual image and I load it in a browser manually just fine.

The resulting HTML does not even include the image tag.  I threw some console.log calls into react-native-web's Image component and I can see its trying to load the JS export, not the actual image:
```
[HMR] Waiting for update signal from WDS...
index.js:85 Running application "react-native" with appParams: {"initialProps":{"initalState":{"auth":{"user":null,"apiToken":null}}},"rootTag":"#react-root"}.
Development-level warnings: ON.
Performance optimizations: OFF.
index.js:204 render image source:  AdaptiveImage {data: {…}}data: {uri: "/packs/Logo-White-Large-30623336086a09a195315f12170a9aee.gif", width: 1800, height: 374}height: 374uri: "/packs/Logo-White-Large-30623336086a09a195315f12170a9aee.gif"width: 1800__proto__: Object
index.js:207 should display:  false
index.js:343 calling image loader uri(source): /packs/Logo-White-Large-30623336086a09a195315f12170a9aee.gif AdaptiveImage {data: {…}}data: {uri: "/packs/Logo-White-Large-30623336086a09a195315f12170a9aee.gif", width: 1800, height: 374}height: (...)uri: (...)width: (...)__proto__: Object
index.js:376 update image state:  LOADING
index.js:376 
```
I am at a loss at this point.  It seems to me the RNW should be getting `_/_/client/src/assets/images/Logo-White-Large-5469ae2c62722b55416c0ca6f1dbba39.gif` as the image URI but its not.  Any ideas?

**Comment by peter-jozsa** [comment]
hey there,

could you tell me which version of React native are you using?
Opening /packs/Logo-White-Large-30623336086a09a195315f12170a9aee.gif URL in the browser shows the actual image?

**Comment by DaKaZ** [comment]
Hi @peter-jozsa I am using React Native 0.55.4 and RNW 0.8.11.

As seen above, `/packs/Logo-White-Large-30623336086a09a195315f12170a9aee.gif` contains:
```
module.exports = __webpack_public_path__ + "_/_/client/src/assets/images/Logo-White-Large-5469ae2c62722b55416c0ca6f1dbba39.gif";
```
and `/packs/_/_/client/src/assets/images/Logo-White-Large-5469ae2c62722b55416c0ca6f1dbba39.gif` is the actual image (and opens in a browser)

**Comment by DaKaZ** [comment]
@peter-jozsa just checking to see if you had any ideas...

**Comment by DaKaZ** [comment]
Lol... I figured it out.  It was stupid user error.  The image I was testing on did not have scalings.  As soon as I created the `Logo-White-Large@2x.gif` and `Logo-White-Large@3x.gif` everything works as advertised... sorry for the bother and I appreciate your work here!

**Comment by peter-jozsa** [comment]
I'm glad to hear that you solved your problem. I started looking for issues but I could not found any related. Have a nice day! :)
